# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
type: Opaque
stringData:
  admin-user: ENC[AES256_GCM,data:EJOFFFw=,iv:oiUVIxFLcm7WLDp+5Aiouvz7/PIm7JLJ5HdNnw/ipzg=,tag:oRCOZLpI5vEmkX8+49f07A==,type:str]
  admin-password: ENC[AES256_GCM,data:TJCWDuD04agUVLiKWbW1/+SB,iv:l5HKZAuQn4d5vxawDbDEbztafCMsUHsdUaHv0Z88Yuo=,tag:fhckHVoGexJAzbLUfYanpw==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:pPMwcmCUIOVcyUWjIDeEVC82D5wf4fCeifYgZjqwJw7xdXlZ,iv:KFHCNofNTJufseyC7VqROOpbyfhGW8L6u63ykmPC/Dg=,tag:Gu3jQe6wMU2lDu4SbQFtIQ==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:L67xkpRlbxdYcJ9GNoZZkfo7RNE2s7FYPMRAecIkkmo=,iv:77kO6iGy+H8MdUAJo11GUXt3GayWmEajJRTv8PYrevE=,tag:d54D7h1Ag7LSDLwnDZ13Kw==,type:str]
sops:
  age:
    - recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMblhROEx6T2IyWm5qSXRk
        N2phSm1vcXF3TXRYZklISXZQNFNaNm9xc2ljCjhPOXNTczVhUE13WWpMTDJZekt1
        S0d5MEF2ZlVoZ0d1eWM5UTVGdndBZEEKLS0tIEZXUWw3alZvU1VkZVdDTE1UaVRz
        cVJ5T003aUU2anlQczliSlR2RFdTMVUK2ulCo+jjH3ZuMNrChnWXFo4SIkC83xjY
        Ri3p0/qEOVlCYcL1N07blcjjIN9sqTpH3s2dPf7u/PJG3Q+p9uuqnw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T15:16:50Z"
  mac: ENC[AES256_GCM,data:FTLyA70/zlsiQWm5z1iOWopIoy5Vs1BDumMTUeJx6jGaq1LDAglAVyXoBShRBZ3pMBVor+t84rbxhWNbV397PC4Q1RfrUMCVVP2+USD6pV4LBvuCdDEj+6Bn56uDZzNjNqWIv7ykg5B+Oq1FeeoRMjDHAdAnb1t6hZpDdaeRsvA=,iv:s+H6WLmgqj5e7bSgFMI3pArYIBQmSVpHfKMtVoosSB8=,tag:0sr+jeEGLHVu3ji9ExUtBw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
