# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-b2-backups
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:h/oCGuInS+kVUJyO7pxcADZEgFYwiexgdw==,iv:Xyhz81yrSZ/1N2WxCczFBYgnm6nOqIhoYhvYuYPiPTQ=,tag:53bpPi5n/S+WwOp0NXT69Q==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:IOMomG9H8QTEzqlA8mAGtN5sdEBxacStJtA4toL6CIXe,iv:ocMNOFjXYnwBbGs6B/q6ul/nJhTA/hDLGsqtwtX+BUA=,tag:lojz1SqapPK9H8xfbiB+Cw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:n+WXpRHCeJJhWavTfKcuKRWlPdcUdwrlQPRAJm9YeA==,iv:86MsasGHDRgN5rzDg99I4btRqn0VoCKvb/oALLCpOJ4=,tag:jEpfpfZuoq3bFkgttYRR3A==,type:str]
sops:
  age:
    - recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQm5BNUladUY2Q0JNbEZB
        bE5CTzUvWWhoSmFmV3AvRWhSVUNYem81N1hVCjdLdGlNTDJLajlCdU9aQzlrcERK
        MUpxSWo1WkVrb25JMzFKVGo1emNpaTQKLS0tIHl5aXhYdmp4MlUyNUJmR0E0UzIr
        dVNkY1M1OTlpY0JHV1BFSFZpQ1hHTWMKO2w+O0bOm9dVmtrxb/WPIVquw0wcwGlr
        ynUhnHIZ8OKIfTCQCj07wgl+I2zJ0ufS5yzRJqz7ksv4ubV3cC2v7w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-14T14:25:41Z"
  mac: ENC[AES256_GCM,data:tU9UZAF4mQIV13hDrJBtvqoAbsCZGRKIfbceu8l+cFz0pYNxTP9yPihdpjGIp4zwb6A84lXEKuk9JLVpv8WMANSyIXUdOyV0GdgZMScJFTKRdYP9IuJ5o0uOymm5WK/k6jZc4RYSxnHoKO3P+/EZJA/C6kQVmwG2RHcvNSan2ww=,iv:+1AMbFB53DTkDi7m3FPoXEu9JZIk6jdilxp9yWN+w14=,tag:wAbKPjuLFqq5upJKFL0Kjg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
