apiVersion: v1
kind: Secret
metadata:
    name: longhorn-r2-backups
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Ru7YPo5QcQhIh0DZTotIdYCGzXst9D7YCjtnki8mC6U=,iv:fTixbDQewTPqduqreT/VaIkn/h7bavH4TiTWHME2zvM=,tag:Db1OXKMOo6y1CpV2NEyLpQ==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:IzcseJ5ZZR68xLb7Bpmw1AhFKQF2iunQ9JlXdR5v34JOQMIzOvYuM9Jp2W4od3fPXTMfmcQsj62ZwVeCM3t2KgY=,iv:tJLSyW+ta1PPwoz0IdybVodYK+k+iMA7MPq9c9l1wZI=,tag:rJgJ6faFPumEFRMbWtqd+g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:aSzdDpWJm2Ffh3oxelNjt5UA31TzHcMfGc1PgPgyhvzYXfztCuhgD9GP6aonQJkavU/UxIuZbSYKU4SDdIg2IA==,iv:XYoYRbQIsGIKG0Th8F28pqXpU+qJX4a0sAg7vP2gbzc=,tag:XdKMHKtndhPNZMF8RF8dRg==,type:str]
sops:
    age:
        - recipient: ***REMOVED***
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcUJGdmpGNWt0TUNEMW9M
            aUdXSXoyREhnTm9LMHFkNUtTUldJbk1STmtNCnNjaUI4V0FpaEJsd1RRemM0RGJO
            SU5Pby8vMjJFaXN3bWttOU5KMGRjNzQKLS0tIG5yenE3eEp1emZRRlRBOGx4dG5C
            Y0RrZFdSTHJ1QTM3QmNOZzl4YVR5cG8KRze/TCHC+JlvVJlYBn+hZXCaXzcYpfb2
            oZ7Zfopc1SvQYnSKSZ0fW6C4slmH96pMIHlSentjKwSZelGafYoDmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T20:35:53Z"
    mac: ENC[AES256_GCM,data:IMBSlbgTD1XuWWFJSzhXLB6sqgU3yz+OGFS+39+wedGGfodbNPDYZqWE2Yz7LzreS0HP3F63e/CxNLVk0sz750Z+q8FkDNk1BPQIOoiPg1+Uh/2U0noYZi5afFb7gvkR4x5nLKfjghFkL7NCh8sQ+KOhn2qcdtJvKsXG2fo+BqM=,iv:D8CYaapkk9k86uSe6kpkfqiu4Ljy2YyQbgB021E3wXM=,tag:rF2w+ELi59u96xnqBZpilg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
