---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - ./backup-secret.sops.yaml
  - ./backup-b2-secret.sops.yaml
  - ./daily-backup.yaml
  - ./longhorn-ingress.secret.sops.yaml
  - ./longhorn-ingress.yaml
