---
# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
type: Opaque
data:
  auth: ENC[AES256_GCM,data:wiGtv68wqaKPXJ2arURk3TyFXT114F9camOf0ahLDDG/rBHARfqvQ/xofI0r+rhgJJOSvKKAo4mqg0VX2PkI6A==,iv:pBgDy1eoIzqWAmSyQK3Y+hDbVE5qL5FAHviyqZRQ160=,tag:W5c5O+Z1bpl9zJWjpOqhrA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNCs2cXlTOE8vVDRUMytr
        cEJZeDNYRE9XcG5sSXdURjdoU2dmaE4vLzA0CmpobjVlR3ZvM2VadEExWWJ5Rm1m
        dkZNOWFQdWRmMnlNTXJySHBVTlJnZ2MKLS0tIEs1TnFKcU1YOWUySHBTUUd5eU5E
        U04rLzR2eGJmVW5oV1FkSnlnTjFLaFUKvtLdZd5mUYvLV8u2iaK6C8pUBDDzqJma
        fNf3RdHbsUBC4tPe3+DxGX6t+ox8oO9e8CDm5F6yxcT8lCaya9EaMw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-10T11:37:47Z"
  mac: ENC[AES256_GCM,data:OLxSdZ++l1yawXeJ4checrqjhC7EmR/nQnMBnswXlwFqcDP3T4r2wr7AYP+EG1GMFsecazbiGQ81kSEMFHo4iGhLysR1e85xdvMkH2ojqAw+ddZ8lsk77F4N3ttmLyfZBfDqz+qHBji6J5NQijRVpZs/M0NnRomHBnejyvCYRkU=,iv:BQtXq3NoiVK7BYiObT1AtUnKIjRt1LKVRaWhw2PgdUo=,tag:YYYAUkjydcFwM7Htmcr03A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
