---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  # namespace: flux-system
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
      version: 1.11.0
  install:
    createNamespace: true
  interval: 1m0s
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Service
            patch: |
              - op: add
                path: /spec/ipFamilies
                value: ["IPv6", "IPv4"]
              - op: add
                path: /spec/ipFamilyPolicy
                value: PreferDualStack
  values:
    defaultSettings:
      backupTarget: s3://talos1018-longhorn@auto/1018/
      backupTargetCredentialSecret: longhorn-b2-backups
      defaultReplicaCount: "3"
      createDefaultDiskLabeledNodes: true
      # systemManagedComponentsNodeSelector: "node.longhorn.io/create-default-disk:true"
    longhornManager:
      nodeSelector:
        node.longhorn.io/create-default-disk: "true"
