---
apiVersion: v1
kind: Service
metadata:
  name: netbootxyz
  labels:
    app.kubernetes.io/name: netbootxyz
  annotations:
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
    - port: 80
      targetPort: http-assets
      protocol: TCP
      name: http-assets
  selector:
    app.kubernetes.io/name: netbootxyz
---
apiVersion: v1
kind: Service
metadata:
  name: netbootxyz-udp
  labels:
    app.kubernetes.io/name: netbootxyz
    service.kubernetes.io/topology: external
  annotations:
    io.cilium/lb-ipam-ips: "${IPV6_PREFIX_GUA}:2000:0:6:14,10.18.6.14"
spec:
  externalTrafficPolicy: Local
  sessionAffinity: None
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  ports:
    - port: 69
      targetPort: tftp
      protocol: UDP
      name: tftp
  selector:
    app.kubernetes.io/name: netbootxyz
