# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cilium.io/ciliumnetworkpolicy_v2.json
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: guest-default-deny
  namespace: guest
spec:
  endpointSelector: {}
  egressDeny:
    - toEntities:
        - all
  ingressDeny:
    - fromEntities:
        - all
