---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/k8s.cni.cncf.io/networkattachmentdefinition_v1.json
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-iot
spec:
  config: |
    {
      "cniVersion": "0.4.0",
      "name": "multus-iot",
      "type": "ipvlan",
      "mode": "l2",
      "master": "enp1s0.3",
      "ipam": {
        "type": "static",
        "addresses": []
      }
    }
