---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/k8s.cni.cncf.io/networkattachmentdefinition_v1.json
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: multus-iot
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-iot",
      "plugins": [
        {
          "type": "macvlan",
          "master": "enp1s0.3",
          "mode": "bridge",
          "ipam": {
            "type": "host-local",
            "ranges": [
              [{
                "subnet": "fd00:1018:0:2::/64"
              }]
            ]
          }
        },
        {
          "type": "tuning",
          "sysctl": {
            "net.ipv6.conf.IFNAME.accept_ra": "2",
            "net.ipv6.conf.IFNAME.accept_ra_rt_info_max_plen": "128",
            "net.ipv6.conf.IFNAME.forwarding": "0"
          }
        },
        {
          "type": "sbr"
        }
      ]
    }
