---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/k8s.cni.cncf.io/networkattachmentdefinition_v1.json
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: multus-lan
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-iot",
      "plugins": [
        {
          "type": "macvlan",
          "master": "enp1s0.2",
          "mode": "bridge"
        },
        {
          "type": "tuning",
          "sysctl": {
            "net.ipv6.conf.IFNAME.accept_ra": "2",
            "net.ipv6.conf.IFNAME.accept_ra_rt_info_max_plen": "128",
            "net.ipv6.conf.IFNAME.forwarding": "0",
            "net.ipv6.conf.IFNAME.accept_ra_defrtr": "0"
          }
        }
      ]
    }
