---
# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
type: Opaque
stringData:
  admin-user: ENC[AES256_GCM,data:pYzf1js=,iv:8GN31lCJddABsmpLf8pLQL2I6twSU/J99lan4o/GuDE=,tag:ct6Y/0NFsZ0VoUYpJllbQg==,type:str]
  adminPassword: ENC[AES256_GCM,data:yqbiOYrWX2KMdWCk14yklTE6,iv:eAskc3qojD+WodvVYZbTDzOzH1TrZYNV1uzHu6xz64A=,tag:oKYDpAdQb2y+khy8YTIacw==,type:str]
sops:
  age:
    - recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1bThSTTQ1WWcvcWJHa3Ex
        M0dOUW9tMmxYd3pVejVVdS9wa01sTVl2aXdRCnZJQVJMNm1Xc0pzb3pJUzU0QmEy
        d2UwY2JrSzU3WUZsWEZ1VWtFd2s4N2sKLS0tIEVpdlpUaVZyM0pULzNIeTR6Y1Va
        cmxXdTBTUHB3MWVtdk1zYmdZeUdsamMKubwXqifOgT483JD3fvTkNoMP5BarByqr
        IsWHhZqASesZkZLSrLYsfuKORHC+GOOBLwYcPxqpPU2a3bzm2huK9A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T13:12:21Z"
  mac: ENC[AES256_GCM,data:jv/Uw1eLjlaAUzQF9NjCWPjOohZ/36ID80KiyOZwvLEYPDvhewxA5kiThqypLbozgRFIDcik1WpcrVUUb/3dACkQ8wwmK9nwPmqZ+ek2WMTEl9Mqg5HXhZOK4/ZZ1o6eU0b1AWxTOVn7y4yUHVN1NKVdo8wcrMpM3wJ8IVGu63M=,iv:TEjs4RRKJdAfNiztOaoHrfmaTGHhzqdbY2v1++iZZJY=,tag:BdtWLlwGzT0pc/0b0px3cQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
