---
# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: chrony
  namespace: network
  labels:
    app.kubernetes.io/name: chrony
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: chrony
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chrony
    spec:
      containers:
        - name: chrony
          image: dockurr/chrony:4.6.1
          env:
            - name: TZ
              value: "Etc/UTC"
            - name: NTP_SERVERS
              value: >-
                time1.google.com,time2.google.com,ntp1.time.nl,ntp2.time.nl,
                ntp0.nl.uu.net,ntp1.nl.uu.net
          resources:
            limits:
              cpu: "0.2"
              memory: "50Mi"
            requests:
              cpu: "0.05"
              memory: "10Mi"
          ports:
            - containerPort: 123
              protocol: UDP
