---
apiVersion: v1
kind: Service
metadata:
  name: chrony
  labels:
    app.kubernetes.io/name: chrony
    service.kubernetes.io/topology: external
  annotations:
    io.cilium/lb-ipam-ips: "${IPV6_PREFIX_GUA}:2000:0:6:13,10.18.6.13"
spec:
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  externalTrafficPolicy: Local
  sessionAffinity: None
  ports:
    - port: 123
      targetPort: 123
      protocol: UDP
      name: ntp
  selector:
    app.kubernetes.io/name: chrony
