# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cilium.io/ciliumloadbalancerippool_v2.json
---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: internal-pool
spec:
  blocks:
    - cidr: "fd00:1018:2000::/96"
    - cidr: "10.96.0.0/12"
  serviceSelector:
    matchLabels:
      service.kubernetes.io/topology: internal
