---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-openspeedtest
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - speedtest.${CLUSTER_DOMAIN}
      secretName: speedtest-tls
  rules:
    - host: speedtest.${CLUSTER_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openspeedtest
                port:
                  number: 80
