---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cilium/ks.yaml # CNI network plugin
  - ./cert-manager/ks.yaml # Certificate management
  - ./ingress-nginx/ks.yaml # Ingress controller
