---
# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
type: Opaque
data:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:iVpxYgKhhyMURDBm0E4SDwD4qAWvmyiG11/luaZVMjCPO0G1QYmMZjY+/w+9vH2mthjhK0yQZzzg6EkdyDjgpUr/5U+XbjGMB06v82UcwLMRyV10Te1nztYp0dgc2A4SPROQtN1dXs7GgImgbKK0Cmz+SFNTPJ+mN/kje6FYLlk7wnz0kQKEZC+QP1++PNmCy5o76F0osCISmQKWH0C4zfXk4v9++AUDDuDQA0/a0IyRxZerZr6UCCi4+5LtwgH7Jnb0xuDxGbsH1uiFhgVeuyUQL/QoBj3sKV1OOh7tBBcbWYKowYkipceyOv7QapHZRPQXNfu3lgY=,iv:MYScz+ObQJKC1E5ieFd1Qj4vU37Ifa2flp06aZiEVlU=,tag:GG4Gu5ddTRulxNUol9zF6g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdHNGSWhaekg3dHhaR3dq
        K1ZPRU43L1pXNGtvK2plOCtFQ0dNNldTaEdjCkVZaHdiKyt6WndydWU4VGl6S0FC
        aVNDWDRyMHMwcEIwelhGZkVtYnhXZ1EKLS0tIHRtU3RLVTRYMENjWDFyR1lzeFF0
        aHhHMHBKTDd6SWdCTW50M2R4ZTZsbVUKWLr7yChU970Uf4aopZWtkiUa0alrp0uj
        q8b/IHUZpewkVRgarLTrCuxRF1Rqgw64ujW2W3jPDxGBv8IhJMOu4w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-10T11:00:30Z"
  mac: ENC[AES256_GCM,data:cUp6MznarQMaAvbgdDox/T4OBWYl5jKEYHgY6fz0lYRkmXGHgVwsXrWjumiamBy+XwxJLWOxcJh0c/cyLG4PuxzDodGA5xdg5g05pTxTz4mjt+zJlAsj/C7QM/94XLvr4uSe2e7d6PcZl9EZlqct0kIHN/oPoTGz5KiHKiolvb0=,iv:7yAqJuOqLfpUuXP7qT++M68vBwXxY9hMoycLQB4TRqQ=,tag:FCr1tMAnPdxnrhD7i49LPA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
