---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mealie-config
  labels:
    app.kubernetes.io/name: mealie
data:
  ALLOW_SIGNUP: "false"
  PUID: "1000"
  PGID: "1000"
  API_HOST: ""
  TZ: "Europe/Amsterdam"
  BASE_URL: "https://mealie.${CLUSTER_DOMAIN}"
