apiVersion: v1
kind: Secret
metadata:
  name: mealie-secret
  namespace: mealie
type: Opaque
stringData:
  OPENAI_API_KEY: ENC[AES256_GCM,data:lPFPVR0WLSyHALL1b9JllECmVnvyVVoBWVjUje3muy5R3gvj1Ht8rcLgeRLwSns5T1fn+TfdQ7y2vK4jyRaiXejzyPVqI6UdKwSwIjELqYqGsOvLMowR0rZ4tHE20C8DoGYxVDrktGBNKwNS5F4Uc79UvqiNbK3CiUTKcC7wc5m3O8U3BidH2dVi/L4B+CSvrLql+21w+JQzZyK0QMMmcp0GGik=,iv:hLiVbYMc3M/VwghkHlNdlK52R3SiSm0dyssd60dt9aQ=,tag:KWciXY5hu1h75a8w5AIETw==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:EFaahtdNWtkH0aMqq3hB/G1IxZwVEz1l5t2vNYzURFRTVjDJ,iv:/IsOD4M6+lYd/liljHeCYVmPcUemIu/Rbld62pArI4k=,tag:PABfaysu5t9xjh+7XtEPjw==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:gbUmOfwv+iumXJ7qvO49FX6DcdKGsgsCFRMA6HnEve8=,iv:el6v12CqZPOZ2UY594iuUF1ncxERCpKi1YA3rMH5eeA=,tag:u+WWVzA29gET2hxnOuep9Q==,type:str]
sops:
  age:
    - recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQ05vMGNXZHhiZjB6MnF1
        VmNUamxSUDJPV0F3WTYyL0ZJd0xzaW5NZzJvCm1SMjNyUkg2Tkw2cVN3VmZOcy9I
        cTduVzJJZ0dtRkRobHlkQXZ2eUY1emMKLS0tIEpKK1pWaWJXUkYvU1NvOWxwQ242
        VjF0YmNTNllzQ2tjKzBiVHF1MG1CVUEKfNEUjXapP/n+4XuIFBrnde6ylVnAESti
        oHAHprb5sjejoIlWFxb2PE149XiR93FJjATyRBzk2JKyHHaQiEcc1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T20:49:21Z"
  mac: ENC[AES256_GCM,data:y+wVrsaf2r0eIgGPOqEo1zImaquWupjhT0fIbWUuAo0Ml9hndZqBYMDcIRIfoCLlPomHnv8GV6ufCNtx+Dl1uoQcT/NllIDtvbW3+n6d8iBahlLUd/ZHOP8XCHb7sx+hgCWPnev5QdP5Z+Zam57XwGQmphl+DxsUsoR/VVUm4Ao=,iv:UdZRnjIQzMbqNjmmqRrwrIEeFYsiSgbB2AVsobPY68Y=,tag:wIlY4tzjJalEzC1geitEXg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
