apiVersion: v1
kind: Secret
metadata:
  name: mealie-secret
  namespace: mealie
type: Opaque
stringData:
  OPENAI_API_KEY: ENC[AES256_GCM,data:lPFPVR0WLSyHALL1b9JllECmVnvyVVoBWVjUje3muy5R3gvj1Ht8rcLgeRLwSns5T1fn+TfdQ7y2vK4jyRaiXejzyPVqI6UdKwSwIjELqYqGsOvLMowR0rZ4tHE20C8DoGYxVDrktGBNKwNS5F4Uc79UvqiNbK3CiUTKcC7wc5m3O8U3BidH2dVi/L4B+CSvrLql+21w+JQzZyK0QMMmcp0GGik=,iv:hLiVbYMc3M/VwghkHlNdlK52R3SiSm0dyssd60dt9aQ=,tag:KWciXY5hu1h75a8w5AIETw==,type:str]
sops:
  age:
    - recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQ05vMGNXZHhiZjB6MnF1
        VmNUamxSUDJPV0F3WTYyL0ZJd0xzaW5NZzJvCm1SMjNyUkg2Tkw2cVN3VmZOcy9I
        cTduVzJJZ0dtRkRobHlkQXZ2eUY1emMKLS0tIEpKK1pWaWJXUkYvU1NvOWxwQ242
        VjF0YmNTNllzQ2tjKzBiVHF1MG1CVUEKfNEUjXapP/n+4XuIFBrnde6ylVnAESti
        oHAHprb5sjejoIlWFxb2PE149XiR93FJjATyRBzk2JKyHHaQiEcc1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T12:01:47Z"
  mac: ENC[AES256_GCM,data:3NocBzsH+efO8eqeM1CoPK7c5S/WrXS3aMQUNaY7S90Ba9qfGJ2sOOE+DiDqReLREoiUqoVkj3s8F08cIwH0O5B6aBhE2rURuQuSJoRr7Q8BW98HPnAmUhOqMIO50nD0kqWTfGDuBtKQKxYYC56xu+PQgXypS5n1jtvRyT4lkJ8=,iv:7vjhEigIvv7o1/JiBmSYoukD0Hm5EAlTG9DFuYgTJbQ=,tag:dhyhMfy/z4hhFzpZrVWxtw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
