---
# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-dns-api-token-secret
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:P/HorK2hD/Qmpkfi5C8NcHqqu6wr02iswAJdu2jrpGRr0DUWlrbUCA==,iv:UzymkxXRX/4tA/+Fdx7mZUqK3AaITUeISmON30GO7N0=,tag:3j/vo6X6IaKgd020w5qE5g==,type:str]
sops:
    age:
        - recipient: ***REMOVED***
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbFBNSU42ZjF1YmxIcDVr
            eVRxYjJ6bkswRXJZMDlUWEllRldMS1ZZbG1BCjlkVEZSOFZOTEZ2bnNiM2tXSGkr
            RTl1T2U3SkFqZmpzL2EvV3c3SkhKQk0KLS0tICtvQWh5L2VmbEZuVWNRUy9qUkZi
            YkRlcG55VnlBM0Z3bkZaaGRTYTBRYXMKq4jh4sbDnmeoiYp0/Mna0QcUyCUjqmVz
            THZLsVnsqKLSJQrLnFsymyRJS0CDNwwxTrrdHQSGAtXth3ZvfxguAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T20:17:22Z"
    mac: ENC[AES256_GCM,data:4EGDRH9oGg4pT9A8sGSuZ0/6ppIw1Xsl4Mt7MNmZMkqW5VsOGREPrkf95+cQB1o7gBZ06S7MzIWaAmPjEcdeOARbzftbHC+JieuB1pAe6VQz2lAxfWyYgFza7tM43zMm/oxFWs4MynOA/CEbRxTtLOEv3cGAUERrPVGbJEvLyVg=,iv:M2cOT0huItzrf8/1qWlDSmbcsR1GszVvxekJUU+EKMg=,tag:UMC3nZwGdkARzUHfXYcsXg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
