---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homebox-config
  labels:
    app.kubernetes.io/name: homebox
data:
  TZ: "Europe/Amsterdam"
  HBOX_WEB_MAX_FILE_UPLOAD: "10"
  HBOX_OPTIONS_ALLOW_ANALYTICS: "false"
  HBOX_OPTIONS_ALLOW_REGISTRATION: "false"
