---
# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homebox
  labels:
    app.kubernetes.io/name: homebox
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: homebox
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homebox
    spec:
      containers:
        - name: homebox
          image: "ghcr.io/sysadminsmedia/homebox:0.22.3-rootless"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 7745
              protocol: TCP
          env:
            - name: TZ
              value: ${TIMEZONE}
            - name: HBOX_WEB_MAX_FILE_UPLOAD
              value: "10"
            - name: HBOX_OPTIONS_ALLOW_ANALYTICS
              value: "false"
            - name: HBOX_OPTIONS_ALLOW_REGISTRATION
              value: "false"
            - name: HBOX_OPTIONS_TRUST_PROXY
              value: "true"
            - name: HBOX_OPTIONS_HOSTNAME
              value: "homebox.${CLUSTER_DOMAIN}"
            - name: HBOX_OPTIONS_ALLOW_LOCAL_LOGIN
              value: "false"
            - name: HBOX_OIDC_ENABLED
              value: "true"
            - name: HBOX_OIDC_BUTTON_TEXT
              value: "Sign in with Pocket ID"
            - name: HBOX_OIDC_ISSUER_URL
              value: https://pid.${DOMAIN}
            - name: HBOX_OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: homebox-secret
                  key: HBOX_OIDC_CLIENT_ID
            - name: HBOX_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: homebox-secret
                  key: HBOX_OIDC_CLIENT_SECRET
          volumeMounts:
            - mountPath: /data
              name: data
          resources:
            limits:
              cpu: "0.1"
              memory: "200Mi"
            requests:
              cpu: "0.001"
              memory: "50Mi"
          livenessProbe: &probes
            httpGet:
              path: /api/v1/status
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe: *probes
          startupProbe: *probes

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: homebox-data
