apiVersion: v1
kind: Secret
metadata:
  name: homebox-secret
type: Opaque
stringData:
  HBOX_OIDC_CLIENT_ID: ENC[AES256_GCM,data:cMiu8e0rYPgjEqW5kI/vYsWwV/Ssqd65lKWeluct0zhDZzvp,iv:K+x4yFTXoIXQkBOeGBoaer8dkeOiYZgJOKnbhCOgqWk=,tag:LkwrQJA6Pg7dW1q/21x1CA==,type:str]
  HBOX_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:lob/TZSTutqM5fv1ke8fbuJQzvoJ2Hts5wdCah3DQ/o=,iv:45KWCUhG5G8Xn4rlZKuXimSYHcs6dONIuROhush2oOw=,tag:p2ShFkkoXDLFiIDBdgvswg==,type:str]
sops:
  age:
    - recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESHZKVDZzelRaSGd0dlhJ
        Q2tYWUk4TE5TZndSSkJERXc1Y3EwTkVwNGcwClJpb0FqWnh1NDFOVnRvbG5FOWpN
        TVh3Q0tIN1pyUG9JVDdkelZscVJNd2sKLS0tIHJWMFptZm9ZOGxDUHhmTDhwVXp3
        emFLbTBueG1NVGJEVURFZjBtd1NBa0EKghNbxbGmXyKubPhwBk7t3cUaG5HETS7A
        d02aiX4eYpiPUbYTBxw1tACdrjidMGSlvv/ISgWnCxt/TEzywVlXXw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:31:05Z"
  mac: ENC[AES256_GCM,data:1cKWXQhtxzgMBeo3KCnFKca8Qg2SjIAL+E7yQPzLWcki07cSO05M2oa3QTBS9dNrVPOley/7Jrw71nsRS6q16myxpbXTZLJFp2ofnGRZTGA9pf1WMgvvFXeqMubS3fDYVlYBjJmddiUbgAizJyVPPmrPOgpOFN1i00q8wjwlXyk=,iv:1IiaIubVpWkqzoKcyvpQWxaq99Trv6lJSgF4ESRkMn4=,tag:6VJIXQn3dKfhrKNcXApb4A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
