---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homebox
resources:
  - namespace.yaml
  - pvc.yaml
  - homebox-secret.sops.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
