---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./ocirepository.yaml
  - ./changedetection/ks.yaml
  - ./paperless/ks.yaml
  - ./n8n/ks.yaml
# components:
#   - ../../../components/common
