apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  TIMEZONE: ENC[AES256_GCM,data:IEMoJHrqlPUgED0SxT5CiQ==,iv:LcMJk76OKOWUYi0a/NV3kUy4ABB625bH3fXeqKT6Qh4=,tag:YnsL2sBicFj6fAfypqL8mA==,type:str]
  DOMAIN: ENC[AES256_GCM,data:Llbmq+KYoVJRi3U=,iv:sBcSmIhgLaZnIoDrqx9Nybbw9Ll3frs6CW6km+76xVM=,tag:tuOARjl7rbnBawvEPLwN7w==,type:str]
  CLUSTER_DOMAIN: ENC[AES256_GCM,data:kfre/VSZJKSAKFqC1QVBvw==,iv:BSxcnHJfaigFLrvk7SIACkl5Svhfc9AdDcVRzB0mtHI=,tag:kE4I0/A0m1pBQxRmHz8yMg==,type:str]
  IPV6_PREFIX_GUA: ENC[AES256_GCM,data:5/AzLs0isjwbDkL0WbPdQA==,iv:hfwq+WmPZDksN+BDejFVWy9y6rFvgdjoXY1hHBF3d1U=,tag:fD/UoFhGIUqlD8Q55hpoyw==,type:str]
  LETSENCRYPT_EMAIL: ENC[AES256_GCM,data:vIaVgPi9mckaqs3GpK1arQiJ23B0YBu4CS8mTA==,iv:KFIm5bVK+sW5ofMjAUFWr2RYZMLTFjy9ty+9fEFzU0s=,tag:tx7GIk+rF7TqcFQlbi4oBQ==,type:str]
sops:
  age:
    - recipient: ***REMOVED***
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcGRVV01nS09qdVlkN21v
        c0NUVEQ0clVlNVE0dXZvUnF3MThqSEhrMlNFCnFlZVJuTkRKOUIydzVjbGE3SUFl
        ODB3LzZiM0Y3a1p4VTQwSzhXcXpZSWMKLS0tIG1SR1RMQVk2Q2JVY2tDQ1pvYW1u
        ZFVTMzZxYmNwOStNRUlaa1liVC9ickEKHoIq3IaPBWolD4b/uBlqDN8CCE65ey31
        +LNye92W6D2LbPMyDSY5txOGY3lAaFkpthDBov2w2TfGLWXGB5rBcw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T16:38:10Z"
  mac: ENC[AES256_GCM,data:MuITlGN3oeKqaz9hxXudokiRFHSjrag2OpQi3cUHelTB1vPVomnxsIg3FUYz/GlyY6JegR4QmxQVJZqn53xoLCvOgixQpw1uN3eOs5tbXCYsGUuoNDP1APzPxgG+Fg/VD2qHvxSl7QH4dsZehS/q9U2BG8AHBeDEDzrmmlmFuMw=,iv:GX4ZKgrsbW9iD4E4unbCyJjt/OBtDRNBGlF4HQ1xz5s=,tag:a63gXIPIUntWgxt4rUkIKw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
