---
# yaml-language-server: $schema=https://json.schemastore.org/sops
creation_rules:
  - path_regex: .+\.sops\.yaml
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    key_groups:
      - age:
          - ***REMOVED***
stores:
  yaml:
    indent: 2
