---
# yaml-language-server: $schema=https://json.schemastore.org/sops
creation_rules:
  - path_regex: .+\.sops\.yaml
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    key_groups:
      - age:
          - age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
stores:
  yaml:
    indent: 2
