---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-spoolman
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - spoolman.${CLUSTER_DOMAIN}
      secretName: spoolman-tls
  rules:
    - host: spoolman.${CLUSTER_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spoolman-http
                port:
                  number: 8000
