---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./kube-system

  # Network and Infrastructure
  - ./network

  - ./security

  # Monitoring and Observability
  - ./observability

  # Home Automation
  - ./home-automation

  # Self Hosted
  - ./self-hosted

  # Web Services and Apps
  - ./homepage/ks.yaml
  - ./mealie/ks.yaml
  - ./homebox/ks.yaml
  - ./bricktracker/ks.yaml

  # Media and Entertainment
  - ./media
  - ./minecraft-bedrock/ks.yaml

  # 3D Printing
  - ./spoolman/ks.yaml

  # Utilities
  - ./adsb/ks.yaml
  - ./capacitor/ks.yaml

  # Development and Testing
  - ./podinfo/ks.yaml

  # Guest ns for untrusted
  - ./guest
