---
# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bds-data
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/daily-backup: enabled
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
