---
apiVersion: v1
kind: Service
metadata:
  name: bds
  labels:
    service.kubernetes.io/topology: external
  annotations:
    io.cilium/lb-ipam-ips: "${IPV6_PREFIX_GUA}:2000:0:6:12,10.18.6.12"
spec:
  selector:
    app: bds
  ports:
    - name: bds-ipv4
      protocol: UDP
      port: 19132
      targetPort: 19132
    - name: bds-ipv6
      protocol: UDP
      port: 19133
      targetPort: 19133
  # Use LoadBalancer if running on a provider that supports that
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  # or use NodePort on a non-managed system;
  # however, you'll need to lookup port assigned to the service
  # type: NodePort
