# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: pocket-id-secret
type: Opaque
stringData:
  ENCRYPTION_KEY: ENC[AES256_GCM,data:LgmE3QXiRPKUcXyr/adovoBlchdve+gzn1SqNX4uRBW6NUCOWsmeLmrAHNY=,iv:EpZhqM8Qb4BoYDUqNyRNwIwFTljdHcJcmUXG/0gveOc=,tag:iWa17Sc6EJ6QJP5RB6Vi/Q==,type:str]
  MAXMIND_LICENSE_KEY: ENC[AES256_GCM,data:802ZdDDYs5u1NtV1LpAIuJnWuMGaluQCcTAqE4rQ0C1u8Fs/u11rjg==,iv:ndg+x8FhzSzkwI15AZwV2Fp8ZGOpyiUz03jp7q9+R3s=,tag:gO9yvkOr1bgxsIRg7DRd4Q==,type:str]
sops:
  age:
    - recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESHZKVDZzelRaSGd0dlhJ
        Q2tYWUk4TE5TZndSSkJERXc1Y3EwTkVwNGcwClJpb0FqWnh1NDFOVnRvbG5FOWpN
        TVh3Q0tIN1pyUG9JVDdkelZscVJNd2sKLS0tIHJWMFptZm9ZOGxDUHhmTDhwVXp3
        emFLbTBueG1NVGJEVURFZjBtd1NBa0EKghNbxbGmXyKubPhwBk7t3cUaG5HETS7A
        d02aiX4eYpiPUbYTBxw1tACdrjidMGSlvv/ISgWnCxt/TEzywVlXXw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T10:49:07Z"
  mac: ENC[AES256_GCM,data:0MAIwCSbCVUX10IKr/RH2Nx8YvhZkg2LOE2480WxNpd9Htr5bt7Ct3mvbJCbQhJ/j3bAyDqOLbKaFQPxv9pVc1Fi0Ba1emoHUMVN4xlUX3DkPyEJu08kBUZgLxslMZWpdLehZrMJdza2b/dj8UyR7s0CioLhL3Wk9YgYafjKWq4=,iv:XGSuKh5ehb2/2YN37WnIKT9SeF4frfwdY9b9HTtnoK8=,tag:8rWbQGLKUIvR3IkWgj9zZw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
