apiVersion: v1
kind: Secret
metadata:
    name: esphome-secret
type: Opaque
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:LgmE3QXiRPKUcXyr/adovoBlchdve+gzn1SqNX4uRBW6NUCOWsmeLmrAHNY=,iv:EpZhqM8Qb4BoYDUqNyRNwIwFTljdHcJcmUXG/0gveOc=,tag:iWa17Sc6EJ6QJP5RB6Vi/Q==,type:str]
sops:
    age:
        - recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESHZKVDZzelRaSGd0dlhJ
            Q2tYWUk4TE5TZndSSkJERXc1Y3EwTkVwNGcwClJpb0FqWnh1NDFOVnRvbG5FOWpN
            TVh3Q0tIN1pyUG9JVDdkelZscVJNd2sKLS0tIHJWMFptZm9ZOGxDUHhmTDhwVXp3
            emFLbTBueG1NVGJEVURFZjBtd1NBa0EKghNbxbGmXyKubPhwBk7t3cUaG5HETS7A
            d02aiX4eYpiPUbYTBxw1tACdrjidMGSlvv/ISgWnCxt/TEzywVlXXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T08:30:10Z"
    mac: ENC[AES256_GCM,data:UeUASJHvBJPyU3E5/T9UyugVPmahoa3f2tKQDlZ6II6ylV/Ir9ksarmzi6+9VZTNrP7WKV1K34E9KE597jUbRHh7VUZCY0ROPRqbQBqAhMEkUqqEvwNDs496jiiqJdDRjh18jwAsEp15oG4wjJwyNT1wiC5R5+vKAqWViUS2H1Y=,iv:R45ycbgaGC0ueUAXPSgS4SsaACLUCyUOO1vP5sHw9aw=,tag:yZw6c0AqmqKj124wzta7eA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
