---
# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: isponsorblocktv
  labels:
    app.kubernetes.io/name: isponsorblocktv
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: isponsorblocktv
  template:
    metadata:
      labels:
        app.kubernetes.io/name: isponsorblocktv
    spec:
      containers:
        - name: isponsorblocktv
          image: ghcr.io/dmunozv04/isponsorblocktv:v2.6.1
          resources:
            limits:
              cpu: "0.001"
              memory: "100Mi"
            requests:
              cpu: "0.0001"
              memory: "50Mi"
          volumeMounts:
            - name: config-volume
              mountPath: /app/data/config.json
              subPath: config.json
      volumes:
        - name: config-volume
          secret:
            secretName: isponsorblocktv-secret
