---
# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: isponsorblocktv-secret
type: Opaque
stringData:
  config.json: ENC[AES256_GCM,data:9N5N6z2941VM5nzHf1DjuVVDkZWrwG9t99t5ZanA4+RUnThkcSIVRpNDwvr5cSbWHt2L+JAklruneSKGZa4XDdSHo8WBjAjRV/yeXNtpU5EELbVSkmFAgBATV1fo6Agyw7LkoGAoduX9MKtR26gTNMNqf+VkLkoCfLArj2Nwsb8sZA8xwIDVIZ/8mq5U9T6a3+TPjacr8WXo8WTVVCibg6OnPbnbJdDtrhMDwQOpKIqyrcKMU1CxZcq99VkLYHD95KMFOs3hdI7qjVMar1Bt4SQctKrh1nXLJeHiUVCCP8sDNrOeiCCLsXpiz6m7XBjNmji41DuJmBf72nJHg37TjcnBqvB6F8naxVevOv+gPGK2IfaVMKyLa5IeDVu4nJk=,iv:8M+uiCt3aEGIMxy4f58QPOPt9sAruHtk07JHQl70jGY=,tag:SsQHTwMmIHq+sua6kIioSA==,type:str]
sops:
  age:
    - recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNjJTampDcTgxRGJyenRD
        ck0wd3dGbVlzS0MxUVArWGxhdzNaWTM5MVV3CjF1ME1oMDRWWHF0WEdjN1ZsM2F4
        R0xMcTVxQmJ5ckpQWWtrUWgzb2NGT28KLS0tIFlvK29weC9CeU82bWJ4NnNuWGNS
        UG9UNnJkM1Bqa0hjbGdLdkVLUE9lQncKZZWT1aJzv4p7hbhKiJIvPdvEJmGeCgTE
        PgofmBpsryoOt4lRT9IbTdR6d9eWdDey405oYUwRQzcVLDP/WJqk1Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T15:01:35Z"
  mac: ENC[AES256_GCM,data:nLyYM7ezgo3QYUskXL+B72w2AtWnP2Vfw32WbpMyN6Uz15VwiuxiNPGAEIp93mesxLkqk5fcMAzXhHRRKw4R8+/iq8wlmQQ/NSzaMlkcxNx9u7biRIWden5/5LcYr2QfABv9oiAzVpf5RT3w7OCHEGwZkW2Fpg3404AnjuZ2TfU=,iv:+wlCyFnx9O5gS/GHFMiQA0ekn7jptHj19AgbYwjEuvo=,tag:08V0hu9sNNI6UO+LutsAXQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
