---
# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
# Source: reloader/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reloader-reloader
  namespace: default
