apiVersion: v1
kind: Secret
metadata:
  name: esphome-secret
type: Opaque
stringData:
  secrets.yaml: ENC[AES256_GCM,data:Ed7G5LjxD8A8ET6PlyrUzRH1FZhl9EpUeIgrELHigIM8cu/4H0tYcZiQtgZZNS0amRStzV4vt+ZEWV+mCbI1+SwAlV3nVO8zVMO9jsjPQoAu/EjUnsaTDzca1zog4/jVg4jqq44R/RUZmxXyyA5WLUs/1uRzHV6JeZ1140UxDJVM6bFIDaQt9jAreCD2yG4mqlwmocmYfipDr8JAcI6am7jkD+Ktkru8Ryo/KOReXhk87XbSAqR5ZK+GaUJwln4pqONoR84q4JoJSMk8RS/C01PpAliB42+GhVEiM+As/p+M2ZfzoAqCTuto48SJ4vGItkdmwZGWl5lBm2lPQvowL+4VFWBVUB8uosjrtpMn6kka9A==,iv:BiwAn/pt+KH/96qz/aJ2Y6l2Ihv4WLGAkRAQoE98a0M=,tag:/lfKDRj59ie/hrlgYwOEbg==,type:str]
  USERNAME: ENC[AES256_GCM,data:311IjzwYqGY=,iv:m5/OABdjhfPJeefojSWPAaH1+GwnXcWS2git5i+OrEk=,tag:F4jLNjZsH/2a33OMTEMyJQ==,type:str]
  PASSWORD: ENC[AES256_GCM,data:dvBO48k0PJir94QjiStlb/6eltw=,iv:ZZnU3iQloY/iT6gtyQSf9OmvyuYVgIkN9Hz1eiVJesg=,tag:1rbnq95DkY4sjAHJIgTetg==,type:str]
sops:
  age:
    - recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESHZKVDZzelRaSGd0dlhJ
        Q2tYWUk4TE5TZndSSkJERXc1Y3EwTkVwNGcwClJpb0FqWnh1NDFOVnRvbG5FOWpN
        TVh3Q0tIN1pyUG9JVDdkelZscVJNd2sKLS0tIHJWMFptZm9ZOGxDUHhmTDhwVXp3
        emFLbTBueG1NVGJEVURFZjBtd1NBa0EKghNbxbGmXyKubPhwBk7t3cUaG5HETS7A
        d02aiX4eYpiPUbYTBxw1tACdrjidMGSlvv/ISgWnCxt/TEzywVlXXw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-28T10:49:17Z"
  mac: ENC[AES256_GCM,data:6d8gkzx2CPSlTAyzM25+2HVgW5UY1wRvilpKbLZ3f/h/oK8pMzIzkvokT7aoXwvctn0fG83DvkTZXyLWYIOkXILaQ6ihv9CCTXgsx/WXTDT+y6uImIIvXbFZQXw0UPwsFRScqnd7BQY+8nIgfSzhNb9i6fjq0n+iCsZgnscwbt4=,iv:pR5L0p/x7dwLLS03i1GmNuvOV/AC+NTQJyGosnJdLPE=,tag:2eO+Qr2sKZJD9cHeP11PFg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
