# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: esphome-secret
type: Opaque
stringData:
  secrets.yaml: ENC[AES256_GCM,data:sKX9r2gHGOe7W0b9GOy6m1MUSqopidzKKs8hM9B6kQ0/uFzgqk2grkCaLfEgB0fxvUVoNXjIbmxjLSy2w8fi2H4P4ZII2LHapzTdAGxDjV3hvcI7FhGDgR+CLBJWz9HzUTZx/abLVxSPJmJpI0XYph0ZOtsnj8C/ODkT1PWgatotoNoAi64Oc9a6k808X1x/bneiTJM5nDCu/CBw9BJ4wOWb55rUDZ9bJZwjE5ogPBVrhprGTVuqWG7ezytOwTwD8q7PAeVc82K73CH7cCD/zxnvD7tJmRdZ+LWyPB4cdLCWBxLtqAaqdMlkInSwdUmf78/DOPUGv4fCrdvARhq7vBBsU89sOIInS+KMHFn6QKSTykjmxVDOTT9kdpQGlAepdu6Dq+V5t+DwO/5Csq6aZWEObp65xNQSv8QudEQmQiA+dXTy0OE44HJvcF594nZeWIXb8hNW2RZcYsQVERAbFc+7f4dz6doh7JCgsMnXfIMNNKG9+/WlDLWsLgAu3IA5aJ5UluY80K0uxW7C3FAqXYTtopd5YBOuJXxtyqIehEC4lkyUL4XuUlcQXxWUpisTgvXwfLuaxbQ4yUo6Ew3DASW1H+Er8qYpjVMTG4ne0kxO1AxPX+VcHwGeLZiA3XW83n9itlq87LuJFXRCybbe6+l2TebW,iv:H55pHHtNNsRAnXiRROczsbY4FRosV8v67XzkZ3xM6HU=,tag:7dWje0HIzPioKZRznja5RQ==,type:str]
  USERNAME: ENC[AES256_GCM,data:311IjzwYqGY=,iv:m5/OABdjhfPJeefojSWPAaH1+GwnXcWS2git5i+OrEk=,tag:F4jLNjZsH/2a33OMTEMyJQ==,type:str]
  PASSWORD: ENC[AES256_GCM,data:dvBO48k0PJir94QjiStlb/6eltw=,iv:ZZnU3iQloY/iT6gtyQSf9OmvyuYVgIkN9Hz1eiVJesg=,tag:1rbnq95DkY4sjAHJIgTetg==,type:str]
sops:
  age:
    - recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESHZKVDZzelRaSGd0dlhJ
        Q2tYWUk4TE5TZndSSkJERXc1Y3EwTkVwNGcwClJpb0FqWnh1NDFOVnRvbG5FOWpN
        TVh3Q0tIN1pyUG9JVDdkelZscVJNd2sKLS0tIHJWMFptZm9ZOGxDUHhmTDhwVXp3
        emFLbTBueG1NVGJEVURFZjBtd1NBa0EKghNbxbGmXyKubPhwBk7t3cUaG5HETS7A
        d02aiX4eYpiPUbYTBxw1tACdrjidMGSlvv/ISgWnCxt/TEzywVlXXw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T20:46:53Z"
  mac: ENC[AES256_GCM,data:JxKjYA1tIiXd1cKi4vQ+j6++ApKnWB5tWGFSFHrHSYlQHWpFKU3PNN9Hwkfy85g8K2Y5xxulhbcKeoBix0fTQew9UVd+iBxL3WADVlXGmEcYgyRf6iw/gxyuiSFeHwPVJtWodYdvMi4ITLMc/4yHxlCi3olhmNTbqpC2nX/qWAA=,iv:TEHfCHvZ+UfHEanQDF/gqi0BzIeeSjwzEI+YX+clLvU=,tag:jd66+/BcxOTPpe6r4K48WQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
