---
# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
    name: esphome-secret
type: Opaque
stringData:
    secrets.yaml: ENC[AES256_GCM,data:DsRHr28TuoJ5heyHyrnVJ2MTFN+7g9KGBtpyBe51KOAxZlOuz1SuGdXMHLzMPyDW9cLwBN1eqOk3iR5ItXRHISZT7lt/42jbqfGdvTqY8Z600LesvFDcFHXdzjosuHRHFr7W7yAJRSe/TtZ3vFwTGbS1UwjpzsB+GF6oGgt/YFZeGI9qJhY3f3/LV0MEpBKHkUYcG5bKr68S6u3lzUgleyDsIpcytKtq9eosTraKQdbawPYUlFwVvq66r4qQ7wCRrWU+BZ657wbk49igIcDY4pDMhNUDM9TIt6URd+ikGsS+Qa12zQxRhnyJPtRmC1G5IyVfFWKVDScjHqTwnSJYy9oFoiMNFhzukOhQTTxMQSmnxAD+f57TFTSU/r+GW2lOVpvBRV/gTeLk2eAOsc/zKsGzDjmAxk+6X3BejPNb5muL/G2U41FRC7YDSluVcHE3R0nS+Aw2Aw5RzcCoFxumnbM5R5SKFt3XdycotEdH0vfvLLpxUXot3HuryiRaxqi0vgQUtZHKsTvktQd04gXm5ZpdVJnvhJzFwNVY6M5u06lVJG1ND9qd3k2EYEeXqCT5vMwivH1mxlkW52PaOCnEK3fmjw6VWaLs1S9f+0nciT7M7H/y/GA7wXbR9OqgdKvTNv10me04oHp3ZO2D/x94CtD6GIh/,iv:l17OdDOye8bE+KhxzG1rraFKJyFxl4V+BQOMUWTDE3w=,tag:k9L5hjL2F/1mdveUjVRHag==,type:str]
    USERNAME: ENC[AES256_GCM,data:311IjzwYqGY=,iv:m5/OABdjhfPJeefojSWPAaH1+GwnXcWS2git5i+OrEk=,tag:F4jLNjZsH/2a33OMTEMyJQ==,type:str]
    PASSWORD: ENC[AES256_GCM,data:dvBO48k0PJir94QjiStlb/6eltw=,iv:ZZnU3iQloY/iT6gtyQSf9OmvyuYVgIkN9Hz1eiVJesg=,tag:1rbnq95DkY4sjAHJIgTetg==,type:str]
sops:
    age:
        - recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESHZKVDZzelRaSGd0dlhJ
            Q2tYWUk4TE5TZndSSkJERXc1Y3EwTkVwNGcwClJpb0FqWnh1NDFOVnRvbG5FOWpN
            TVh3Q0tIN1pyUG9JVDdkelZscVJNd2sKLS0tIHJWMFptZm9ZOGxDUHhmTDhwVXp3
            emFLbTBueG1NVGJEVURFZjBtd1NBa0EKghNbxbGmXyKubPhwBk7t3cUaG5HETS7A
            d02aiX4eYpiPUbYTBxw1tACdrjidMGSlvv/ISgWnCxt/TEzywVlXXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T18:02:34Z"
    mac: ENC[AES256_GCM,data:uI+rkuvq1JyOrIuc+w89vEcFTXNF8CoA/qHYB56cJOeZ8MHQUbNHeHOwa+uMzzUX2dvXAUsXKR6YEWxjbtlZIr1KCc/xdr7jNS3fTVceiCUc73mbU+EvFXPoGYDc5geRJ3Mp4CNIUlpTwxoVYPLue0iRzBnkskLeI6STLnn8WlA=,iv:PeuLrpezXRqhK7sc6rmnN1MqsfvEdnkXgy5Ox29afp4=,tag:cyE2ABpqAQrRPKzNbyTUWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
