apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
type: Opaque
data:
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:YHngFtZJXyoiRDsF,iv:GiQ8utnEfHPbWjo0dsUG552Ez0nsCeSd5bpATmw+9TQ=,tag:r352780eYzolSIvtITOyFg==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:4tOF0bc76psjCthNjePZIpgSIs+YvtjxLbJswlftQR4XmeHz1Hd/RTkTJcQ=,iv:zaWdRLe5pLzjcBqe32uPLdXdvJaIk9+on3lZenYeYZM=,tag:/VFXFxAz0OQukPsCcLHmGg==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:kGGKcRTuldFcVCciD07GboQzRikKdpB44t9574QErXDCtWIhqS1y+4RqyD2d817lsp4byvIUaxEgCbX6RY25NzSm4RWYC3oeMeU/PGjIKZg8eZgq24CplQ==,iv:znwhb+oZaZ96ksQ6r4tVnFIDiRlUoZpsjTaQWtCRegI=,tag:XTU6oz0QXROMZSH/dcey/w==,type:str]
stringData:
    rclone.conf: ENC[AES256_GCM,data:MXyXFbFPlIB3yVzc16sd/OVhDGdHyJUolIncRCAc4g4iGl1gF+wr42xoWHFGCMUc39FnIvrvvGqhHrAz7MB6QgOy/XY6jRQA/LbBEEsS3F5JKhZkm8c/g+0RzhQJUJvSrb5WUW6ePhu5DfGtky0IZ2r482hkqvj+JnwWf25bps8R+x9uTjS9Xu7wlp5gQ/s8HQyID+dGAQ5qhXmzrdPaBDVlepJSVy47FvVRVjvmJ5+IFJGaXDRdr1RfUrkyh+vkUTGo/oFJqxyNr5Yvp8LTrc9BX8rogJiZbOpGMptMNY+sC39XhP4LXcAeRXausH87AAR3tTGXKxY30rUAdW3WsOwYeyzq/1KnetA/2ywjedvrcnZu1UwhBhnVwLV64ArTA8Sjzm0/i8YgXO+KGBwHTGpOMW4e0V4YWLek1tV3Cnr61qrBpYSWQ9RGqCvwmQ3Moq+5bT5xkQgFSTvqhsaMM4sWH3ybqnHDskcFKn1YNqNZhhWy8NFT9ByU+Wzm4e9kx8qg7PRK/Des1p8wScR8eu+BVsdiB8SdUuRFkMq02YpP6TXkZDPkkzeELbsKxFPAvvCShMPdtyLN15I1RePH82ReerKA8mT9MxBPoJmiedGVHBbI26pwOLFRWj93sfzoaLhOWwiNNQP97bv3dTY2G8+U7fA1vrTABpLDK6rEYpGdj5Bp7iQYFTwFRA==,iv:tNNtIpn78VSKXQVv4HqxG8mOo1iimd3Wd0iR1/g2S90=,tag:ZSS5SKdfdMQyTEBCJJiQBQ==,type:str]
sops:
    age:
        - recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SXJoUnJFZ0F6bVBpajN3
            RUJTOGp1NThVai9iUDNXcUpIcytnMzJVdm5VCjhmdVduR3ByeHR2YXBNWW90TXdj
            MVM1REVyRzBFQmUxWFZnSTZTVGdJa2MKLS0tIDBaZ2hyd0ViVUVmQURJamxzeDhJ
            UjFwSk12Wkhtd1JoelZBRkZBbGpIYzgKF91h9XYQnjnlQlR+0c1xqNFYfyCaybqF
            nZG1eCUnqebQatNs7vcjcpGt33dF+vRzFaH+CvY9rg9ovAejdkNPYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T10:50:12Z"
    mac: ENC[AES256_GCM,data:yQsc/+T+yJ1amAAHWv++MrqeKRshlBLmGLm6UxoCQ+IiTX+WVs/UilB3DQ3GZgK3KN2e+HtEkM3w8vKAF2ZGiON6P7nRvpiXMkJ4yX5txYFzJB3cVEuehiocGG3qa00Anf55IIldp7kkfwGbU02IinbtKixA6k8SYzlhva/lJa8=,iv:BYaXAKh8PW+l5yN50rDA+QHg/B9dFeWqWvCiJiwYDL4=,tag:J6B1Kcpz4uPtzbEjwdWmxA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
