---
# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: paperless-secret
type: Opaque
stringData:
  PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:rzlpxbP7Qg4=,iv:ux8VLQ04vTQ9nzq9p1EgEQw0Gcl8i7SDGu7fgOzO6qM=,tag:U3UDHm/+Dqbfaq08Sst9mw==,type:str]
  PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:zKkd5WdMfIsL0WpEDsqPxHWq9Yzsum/CDbxWUtVl5FM=,iv:tHDDzEkj1CfzF8WogX180/oHxDRNVJ9ATJZj4UMXVa8=,tag:tA2ZXjaEuCgHqXM42MJ5Yw==,type:str]
  PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:Fm23S7VAEJsr9bOBgHPbhyynP0g/jDTu+w9gZ1BH782gvdVnh1t3M2ZQ61qj6p5cNu9KlNq5Rlkkyt/3GAPbvQ==,iv:ejD0MLDO/7sTFvEw8hK0lCjwiSnbKpACq5VkDF7aJE8=,tag:A2cQGA5kC0IU5DeONPgd7A==,type:str]
  PAPERLESS_APPS_ALLAUTH_OIDC_CLIENT_ID: ENC[AES256_GCM,data:GVumxc3wWtJKEtsD4RKdofQxwQqsZkizUSv7HYDSvZSm3zGa,iv:kvG1AoDgM2fIEo7kpNVPXQk21ocp1yv0oqjNRN6MVHo=,tag:Y2LAnMOmosetFw97v25YSA==,type:str]
  PAPERLESS_APPS_ALLAUTH_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:AbL9oVNkBc1/DAhB6Sa5+4PUT9okM9Z7uWCeIwFI/L4=,iv:bvPjQpHpIF8gN5I8KofDk6Bjtt1R2QhCtHTCK+/sLuU=,tag:Stp7fNcjGiX2WBcqipuFSQ==,type:str]
  rclone.conf: ENC[AES256_GCM,data:MXyXFbFPlIB3yVzc16sd/OVhDGdHyJUolIncRCAc4g4iGl1gF+wr42xoWHFGCMUc39FnIvrvvGqhHrAz7MB6QgOy/XY6jRQA/LbBEEsS3F5JKhZkm8c/g+0RzhQJUJvSrb5WUW6ePhu5DfGtky0IZ2r482hkqvj+JnwWf25bps8R+x9uTjS9Xu7wlp5gQ/s8HQyID+dGAQ5qhXmzrdPaBDVlepJSVy47FvVRVjvmJ5+IFJGaXDRdr1RfUrkyh+vkUTGo/oFJqxyNr5Yvp8LTrc9BX8rogJiZbOpGMptMNY+sC39XhP4LXcAeRXausH87AAR3tTGXKxY30rUAdW3WsOwYeyzq/1KnetA/2ywjedvrcnZu1UwhBhnVwLV64ArTA8Sjzm0/i8YgXO+KGBwHTGpOMW4e0V4YWLek1tV3Cnr61qrBpYSWQ9RGqCvwmQ3Moq+5bT5xkQgFSTvqhsaMM4sWH3ybqnHDskcFKn1YNqNZhhWy8NFT9ByU+Wzm4e9kx8qg7PRK/Des1p8wScR8eu+BVsdiB8SdUuRFkMq02YpP6TXkZDPkkzeELbsKxFPAvvCShMPdtyLN15I1RePH82ReerKA8mT9MxBPoJmiedGVHBbI26pwOLFRWj93sfzoaLhOWwiNNQP97bv3dTY2G8+U7fA1vrTABpLDK6rEYpGdj5Bp7iQYFTwFRA==,iv:tNNtIpn78VSKXQVv4HqxG8mOo1iimd3Wd0iR1/g2S90=,tag:ZSS5SKdfdMQyTEBCJJiQBQ==,type:str]
sops:
  age:
    - recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SXJoUnJFZ0F6bVBpajN3
        RUJTOGp1NThVai9iUDNXcUpIcytnMzJVdm5VCjhmdVduR3ByeHR2YXBNWW90TXdj
        MVM1REVyRzBFQmUxWFZnSTZTVGdJa2MKLS0tIDBaZ2hyd0ViVUVmQURJamxzeDhJ
        UjFwSk12Wkhtd1JoelZBRkZBbGpIYzgKF91h9XYQnjnlQlR+0c1xqNFYfyCaybqF
        nZG1eCUnqebQatNs7vcjcpGt33dF+vRzFaH+CvY9rg9ovAejdkNPYw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T19:06:43Z"
  mac: ENC[AES256_GCM,data:2lT5Vjo/f5nF2Yyl+G0Qf06v6KkyC7JltTTJtzFcmu70tpH/wivyxuiuW4YbtsWfuT6i+YYJ/9Lkyq1YPM1vXS6saK+HLrVHL1dnpmyatiHZt08T7sj4PefbCHAjFLtrhKDRAkDQ+5Zea2XUx2S2gaH9GYIkLf7twsw3E/ZBVzg=,iv:doO95npxwt5LGUN+ABieO+yRDs8M55gyJeKV+roQXdk=,tag:vApK0azxXOGjjfmgH5015A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
