---
# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: homepage-secret
type: Opaque
data:
  HOMEPAGE_VAR_CHANGEDETECTION_APIKEY: ENC[AES256_GCM,data:DkXrgdlYZxkthcggw3uLKWfuqd7XWcLXc60hqbaLn79i/a1Bx0jyoCOwIdM=,iv:Hvw4VekXG9iiyErhgl6ZMVeW/kw4wn5gM7FPwoZuTCA=,tag:jFDZlYT5jJ0LVpVS4SQKXg==,type:str]
  HOMEPAGE_VAR_MEALIE_APIKEY: ENC[AES256_GCM,data:UvF48HnI3+yPZMBl9A2WjuY6sVoTEUT3IsAEUcSTV4CkkZpn+oB0QMBqU+m6VEFib1gEVV+94i1LrXoqX1Kegv8WyLCLM2zdElq6wAVc2He8kcmv0QfbAGlQ5FHX27ogH7Q4NTUfgsc2gM0yqstr6/ig2PLbd8Um/rB4dioX2S9qDwYiQnjbqL9AJVqVN+HYS+8BX2YCbsjzxPJb2Ka9Yu9Oi7nEnAxeO03Mi52uqoN0n79zakvjbk9OUsn58DzRZKxhPc7Vh+dAvw8IXm+/lW+j5+ME7+7nehZKDlYZaIxlcRZ1HrfezwxWDvUe8D9hsLl/994Tp9DV+fV7gAXszdZ1gxpDhc9Ou6Ufp2qvWdQ+mTiLaSGgxIMX7snOJnQ3ynN4i2dBJYqDoEL3p6JDFMAKyNly8MgekQKdK9ulN4VuxnQxfbZqnY7TLk4=,iv:ryUta+zxS/PeiwRXSJYLIiLv+M8G2Tk2r5wo9rH4my8=,tag:8I29xKnUZft020f78vG1Pg==,type:str]
  HOMEPAGE_VAR_PAPERLESS_APIKEY: ENC[AES256_GCM,data:JiX+1smW05yqEFv/i1prt/9wB7C2oJEwc+EcmAZYqK6aBqaSXtDN9LMDJeFoQM7y7T1kG7C7uvg=,iv:xVuuqy+Wq2SS18WS0PyLTtLhjXrhL++8UuLBDSOByRk=,tag:1P2vw9kiSMir58TjC32OgQ==,type:str]
  HOMEPAGE_VAR_HOMEBOX_USERNAME: ENC[AES256_GCM,data:cGR9pgy48feyY2NQuyIJWrnQMOPvp/xR5E3WobaT+pk+uNur,iv:+5iYx22eU1yxKPke10wiCMgifYTSzOtgPnome21H4RA=,tag:llEXeqtKF5/Rl0TK+lcEFg==,type:str]
  HOMEPAGE_VAR_HOMEBOX_PASSWORD: ENC[AES256_GCM,data:gW+pnPyta1fWjR6T5u9WV8BJV4XWezzAZizd1Q==,iv:6FBwxePwfCvkya4FMgVU0yo55QpjDz464Oh2OG+F3W4=,tag:RLmQr5UMZIWMbucfERpHNg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbHBDQ0FIZGozaUpVdW10
        eUgyb1IralZDdmxpVkhIbkkxYVVUU1lRQWlRCnQrMWlQZTY0eDB3c0lXaGJudmVa
        eXppdzRGL3J6UUVGR2taSlNkaXJ3ZmMKLS0tIE55S3dlNjhzMTYyRjk2aU9aNUw2
        WkpzOGNrK1I1UnROenlVQ0tXS2lnK2cKBlovDCRrXCEgnjm8PotUerMrUHRZXeFv
        r6prDOwczqtg2zz8svTd1HfzYUC3zRuGmxg5o1zab6wt6b+t0oO+kQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-30T12:28:15Z"
  mac: ENC[AES256_GCM,data:1YXjLtcUDxodE7n01k37wmB3WBzFis1Xgg1K77esfOy7eazdO1cLq9WiXs5QsKET3SUI+Yb/DDWpTIULApw8wqtAuNGyPoCerQGPHfrn3oWpGSieQwSuKzLq4MjFGFTFBzHY/92sA7EU0Y+QsxxIfS90Nc4RZI1dFZiwRiiKKI8=,iv:YbF8w2EJETUSAMNV6Uq1AQOKJspSJTNXZql+dhDfcsc=,tag:k8QyeoNx5y7v3zDIOUoUIw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
