apiVersion: v1
kind: Secret
metadata:
  name: bricktracker-secret
type: Opaque
data:
  BK_REBRICKABLE_API_KEY: ENC[AES256_GCM,data:RoocZTRfa4u/P+2BuYYJDhuDpaDfjXtk1aj9xdi33WiNRNdZHJ3rfSeI96w=,iv:wz2UIXAQNKHmqgzoR4FSkZeBntBEk/AcNK1zXxYMzYU=,tag:2ndiNZDqajdvTthDD91pSA==,type:str]
  BK_AUTHENTICATION_KEY: ENC[AES256_GCM,data:c3fHUikp/D8xgs1iXdVudKa5QdL0Gv4pBcnpOQtARkH9caF27rrI+uoQSkRCKxTv8XFqD6+A/AvRNtjwth2zJ/+BkgYCG0tW/pDBcAplFXZA9EE+SnRdZw==,iv:G43+mkjLkPKKpHtEMgQ3txudGiqw68/B4kB0Te/Eeyc=,tag:VsMnrOjJdhWplMayo43DUA==,type:str]
  BK_AUTHENTICATION_PASSWORD: ENC[AES256_GCM,data:z7s4SUyOOOWsVoa02nQu+ZXpunz7H1pb,iv:c/9DWBY7yjaXRLinyJ5K/a7/Gbpj73J9oyHaOCrVnzw=,tag:NsXaaMo2a0+oYBtyv7JPfg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByR0RNd0xNbGlZNzI1TEJB
        bElkQ1pmL0x5aDVTQ2tLcGl5S1NmVkRIekE0CmdEOXF6SEpicWFwZWMvbXFjUWpJ
        WjNMQTdUUTRMRkV2K0FYM05yMHpNWUUKLS0tIFc1NGU2dThNUnd6V3Zld1BYeXBV
        WjFSTGxSbmFraUtuVWxzcy9uZEx3eU0KrKaQOS3egP5t+o0oCyb+xLreGdRfXn/F
        oqay8JdNM+0hQr0CpSp+vnhTPS1R9sfQW+ffBp0X+0pVgCqEiRLahQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-04T13:11:00Z"
  mac: ENC[AES256_GCM,data:N/Z4Kj3yeV8v+SBDK94TbAxGi4q9bmu5OlW1adJ25NKtIAb5++QRb+nyF6GEgIQgfBVJXShfXBcOWIgXGZeV/JjKTWLsNzmsTiHRjPe1HnOY/aGW7R6jTlh+48ImJL2dwiOs1AMkvO7tt0elzAdO5WfLL17Z5NpWW2nnHg7dEJI=,iv:KrZcfjB5dNXgSOi+2QTh6Tf4YAnFic24skoJhN3j/Iw=,tag:trFJeELiqMrP4bdwN/lBIg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
