---
# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: adsb-config
  namespace: adsb
type: Opaque
stringData:
  BEASTHOST: ENC[AES256_GCM,data:NNJlW/jiCLLUZD1p6M7C/7I=,iv:lqegwmMG0uT17hWGwuC1QKHqLS7T2FmS19WeW+L0kYQ=,tag:DTwOpnZSAWNx/zk84rzoHg==,type:str]
  FEEDER_SITENAME: ENC[AES256_GCM,data:p6Lxas1phUhtQA==,iv:RQhbLoHtFRGmvIi9+1hZZDnyZrKcK+UlBqG0tHtMT9o=,tag:tyI/WnXwyZaZBc8tIXK9JA==,type:str]
  FEEDER_LAT: ENC[AES256_GCM,data:pammaomXeQ4=,iv:+Cq0lrPJAIopYoUSgV3z79m+KdtBFjujaYKWX6cHbMs=,tag:kz4fsAuYek8wx0X3i09nRw==,type:str]
  FEEDER_LONG: ENC[AES256_GCM,data:AyQfIaVyRA==,iv:7A3FtRypNCYCPazDv4vLbi8VWI7R/KD78/7oNpdAj5o=,tag:yD3oNn3t3ryPvII4I5FJow==,type:str]
  FEEDER_ALT: ENC[AES256_GCM,data:XQcD,iv:a4HC/tbQs6G+9ra7Octz/q9Ild87i5N9Kh8drPLxYJY=,tag:pDZXAIwvCxn5lIiREamhPg==,type:str]
  FEEDER_TZ: ENC[AES256_GCM,data:fD+t9gxEtA==,iv:hVALKVzX4N5/gtSBpP1T7OetMapOzKVPVvOh297qh/U=,tag:jV0SE6lOdC6m05sKYccczQ==,type:str]
  FEEDER_UUID: ENC[AES256_GCM,data:2g3KkHY3wjFpRGe+CYCh5CR1fUNNzs1ktyM1dgpDq1w3Zt/x,iv:mu7nH30xTJuxI7IN2kIesiRKn+zSIrZEy2ImkrJF9lo=,tag:PHrjy7+3HNweEhq38X76vQ==,type:str]
  PIAWARE_FEEDER_ID: ENC[AES256_GCM,data:dTXusTIY62bqZ7jw6o8y0TmKmbFfPXCsaCcA8BMgoEvQpDTE,iv:OqWUL213HwT9nvHxiRtqYq0kVceJpgjH6YULfXZlZZc=,tag:RQ16ym5MBtBDUBlKRoPb/A==,type:str]
  PLANEFINDER_SHARECODE: ENC[AES256_GCM,data:IbyxONt8fC2lFAWS4Q==,iv:ewGA7eYYN7fcnE4xBWY0bG7E4K3COC2TpKtWEAKIBuo=,tag:43rUyCd3ep3GoLWbUD6Bzg==,type:str]
  FR24_SHARING_KEY: ENC[AES256_GCM,data:HLn2OhW/O1WtQ72WXBXN4w==,iv:FIanUE+26v9IRJKmp2LArFSkIkcxkrjgjtgS9tFRjFI=,tag:8TeH01j1ECYR3o4Ey9VoWw==,type:str]
  RADARBOX_SHARING_KEY: ENC[AES256_GCM,data:QbmBMrH75nPjKYCaYsrCvP7LdZv5jfmjZIGq+sI6/xg=,iv:uLXNhhsDJ3MXQmUFaUvNZ5/BU27s4RA2bjPiHmQOhwI=,tag:Qvg7vAOlY+ZzquWjbb9ikw==,type:str]
sops:
  age:
    - recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByKzAyckdSWW5DcmcybXQz
        S2ZvUHQvQVJvaWZ1VTRXbWZNdXM4TUtyOWk0Ckg2T0NQc0RGeWtkQUxkMCtZbktJ
        U1pBM0NOYWlvQ1JCa3k3ZVQ5d2RWeUkKLS0tIDJDdWYyNlQ0QXdobS9UZEtpeXYy
        MVoxcDhLR3Q0QUREdUtQVmNTY1R2b3cKJQqYIkrBsMmuScJhe/c86U8Mu2ttBSPE
        QkJ/akBMFnqKXe7ueOe6g1peO/TyCMFuSdzwsKe3sVo2q/qr6HxpNQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T13:06:01Z"
  mac: ENC[AES256_GCM,data:ytfQuL7uN79jHxFizhWFBbePewWNZVOA9wqOms/6LrJ8aqcLrJNV3JMLdLxNMvYdLGEWi7uULzx3dvRlQg5jAYXsZz4xj7aMvdpx8+jcAR/JJGhJMn9376uJZPlkdBCK9Jgw5sDuz57cJ0vMu+NHWOHI+jLTm9PEbd2xVMPVoUE=,iv:aXl/HeBNEILRqj5rw/Z5uDyGOqxdirMclQGoZ8zbxrM=,tag:NHppxuGoJYURpYSPwZBqwg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
