---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-flightradar24
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt"

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "fr24.adsb.${CLUSTER_DOMAIN}"
      secretName: flightradar24-tls
  rules:
    - host: fr24.adsb.${CLUSTER_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flightradar24
                port:
                  name: http
