---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flightradar24
  namespace: adsb
  labels:
    app.kubernetes.io/name: flightradar24
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flightradar24
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flightradar24
    spec:
      containers:
        - name: flightradar24
          image: ghcr.io/sdr-enthusiasts/docker-flightradar24:1.0.48-0
          envFrom:
            - secretRef:
                name: adsb-config
          env:
            - name: TZ
              valueFrom:
                secretKeyRef:
                  name: adsb-config
                  key: FEEDER_TZ
            - name: FR24KEY
              valueFrom:
                secretKeyRef:
                  name: adsb-config
                  key: FR24_SHARING_KEY
          ports:
            - containerPort: 8754
          resources:
            limits:
              cpu: "0.02"
              memory: "100Mi"
            requests:
              cpu: "0.004"
              memory: "20Mi"
