---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: adsb
resources:
  - namespace.yaml
  - adsb-secret.yaml
  - adsbexchange-deployment.yaml
  - flightradar24-deployment.yaml
  - flightradar24-service.yaml
  - flightradar24-ingress.yaml
  - piaware-deployment.yaml
  - piaware-service.yaml
  - piaware-ingress.yaml
  - planefinder-deployment.yaml
  - planefinder-service.yaml
  - planefinder-ingress.yaml
  - radarbox-deployment.yaml
