---
# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: piaware
  namespace: adsb
  labels:
    app.kubernetes.io/name: piaware
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: piaware
  template:
    metadata:
      labels:
        app.kubernetes.io/name: piaware
    spec:
      containers:
        - name: piaware
          image: ghcr.io/sdr-enthusiasts/docker-piaware:v9.0.1
          envFrom:
            - secretRef:
                name: adsb-config
          env:
            - name: LAT
              valueFrom:
                secretKeyRef:
                  name: adsb-config
                  key: FEEDER_LAT
            - name: LONG
              valueFrom:
                secretKeyRef:
                  name: adsb-config
                  key: FEEDER_LONG
            - name: TZ
              valueFrom:
                secretKeyRef:
                  name: adsb-config
                  key: FEEDER_TZ
            - name: FEEDER_ID
              valueFrom:
                secretKeyRef:
                  name: adsb-config
                  key: PIAWARE_FEEDER_ID
          ports:
            - containerPort: 8080
            - containerPort: 80
          resources:
            limits:
              cpu: "0.05"
              memory: "100Mi"
            requests:
              cpu: "0.01"
              memory: "50Mi"
