---
# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Service
metadata:
  name: piaware
  namespace: adsb
spec:
  selector:
    app.kubernetes.io/name: piaware
  ports:
    - port: 8081
      targetPort: 8080
      protocol: TCP
      name: http-map
    - port: 8088
      targetPort: 80
      protocol: TCP
      name: http
