---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./chrony/ks.yaml
  - ./cloudflared/ks.yaml
  - ./multus/ks.yaml
  - ./netbootxyz/ks.yaml
  - ./openspeedtest/ks.yaml
