# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secret
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:BPUojeFc85tzqqPqXzAAjpIjl8CThZAZgVwItKn9hQNtaQnKhPDJ7mvIcD4=,iv:i1TS5zejpZKMcLqP7GMjf6VaHSm2XqUGxzJ4NkPnRHQ=,tag:QXHuxP9tJvOe+aLYdeNnIQ==,type:str]
sops:
    age:
        - recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eTNOenlwOFhrNVFwWkhQ
            a0JtQlZsdkdkeCtEZEVxTFdINGhKVG9KalU0CmR3cXhkMEJ2VGY1cWlqVElQcXpG
            RlVUT0MvaDcvVUR6L1lhVy9FSnFzUWcKLS0tIEZFc28ybUxpUSt0UFpNZisySUJv
            R0QzT0ZXRVhzQi9MZHp6cmM3Z0s5V2MKUecz0rV1tu9urEtD8SfBIsm/Cc1RdOBp
            W5VszTkhK/HabgyonhKG/U5PaqtsrzrgG9QA93vi3v9VQcp/2Wz/RA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T22:13:10Z"
    mac: ENC[AES256_GCM,data:YVNkaGLhyyBXRPKzB0kCEdBKg9CU3EbEPqIAanqsUA8NzFS5l5NDltyz9Xsx9HO2ORcenpHxPfRJkq9z6aIjoNWKYX3hkM6n8nOVTd7tYLxyCNl5OtCXoDdz6C8GJhkdSVyVkk4RhG/Vcxjny5lxyhK8ALaboiKgU+hj/+b26q8=,iv:iVA9N6TPQDxlLxuBuzFJAjzZw4CZVG+/6dhpCEtHEl4=,tag:1PHXi8+zTpVm9B4RcsT3Ag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
