---
name: Validate Talos Configs
permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: ["*"]
    tags-ignore: ["*"]
    paths:
      - "talos/**/*.yaml"
      - ".github/workflows/validate-talos.yaml"

jobs:
  validate:
    name: Validate Talos Node Configurations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Install Talos CLI
        run: |
          curl -sL https://talos.dev/install | sh
          talosctl version --client

      - name: Validate Talos configurations
        run: ./scripts/validate.sh talos
